### PR TITLE
ScrollChildrenIntoView flag to indicate if next layer of progress bar…

### PR DESCRIPTION
**Pull request by DanielHartl**
…s should be shown when progressbar is on bottom of the screen

### CODE REVIEW

**Comment by DanielHartl** [comment]
This should address issue #36 and #24

**Comment by KrisztianKaszas** [comment]
Hi,
I tested this solution, it spawns a child correctly, BUT the ResetToBottom Function will fail to clean up children if cursorTop > windowHeight (since cusorTop reflects to the buffer and windowHeight to the window itself), so that the Child will not be cleaned up.
Maybe the windowHeight should be the sum of Console.WindowHeight und Console.WindowTop?
Best Regards
Krisztian

**Comment by KrisztianKaszas** [comment]
Since I do not have the privileges to commit, I just made some minor adjustments in order to get ResetToBottom to work when Console.CursorTop is > Console.WindowHeight.

[ProgressBar.zip](https://github.com/Mpdreamz/shellprogressbar/files/3022853/ProgressBar.zip)

Here are my changes highlighted:
image

**Comment by Mpdreamz** [comment]
@KrisztianKaszas if you can submit a PR for this that would be greatly appreciated :+1:

**Comment by Mpdreamz** [comment]
Or @DanielHartl if you could update your PR of course :smile_cat:

**Comment by Shrafe** [comment]
+1 for this change, would be helpful for my use case.

**Comment by Mpdreamz** [comment]
Thank you @DanielHartl @KrisztianKaszas sorry for taking long to get this in.

I took this PR and extended it with: https://github.com/Mpdreamz/shellprogressbar/pull/57

Which is now on `master` will look at releasing this soon.

**Pull request closed without merging**
