### PR TITLE
Converted entire project over to dotnet core

### PR DESCRIPTION
**Pull request by codejnki**
Hi, I wanted to use the shellprogressbar in a dotnet core app I am writing and the current nuget package doesn't support it.

This PR converts the entire project over and fixes a couple of bugs I found along the way.

Let me know what you think.

Mostly a rewrite of the project to support dotnet core
Fixes a bug with child bar rendering
Removed calls to reset WindowTop because they aren't supported on Mac (and probably Linux)

### CODE REVIEW

**Comment by SCKelemen** [comment]
@Mpdreamz Can we merge this?

**Comment by Mpdreamz** [comment]
Oh man this PR totally flew under my radar, travelling at the moment will look at it soon.

**Comment by da1rren** [comment]
@Mpdreamz Any plans to merge this?

**Comment by Mpdreamz** [comment]
Absolutely, diving in first thing in the morning.

**Comment by da1rren** [comment]
Awesome, if you need any issues fixed let me know.

**Comment by codejnki** [comment]
It has been a long time since I did this. We should probably update this to use .csproj files.

**Comment by greigs** [comment]
Yes please to csproj suggestion!

**Comment by Mpdreamz** [comment]
Things are moving: https://github.com/Mpdreamz/shellprogressbar/tree/feature/dotnet-core 

Everything builds and compiles and runs. Need to update the build (packaging/signing/versioning) and then look at the x-plat aspect and cherry-pick some of this PR's fixes (WindowTop).

**Comment by Mpdreamz** [comment]
Closing this in favor of https://github.com/Mpdreamz/shellprogressbar/pull/14

Thanks again @codejnki 👍

**Comment by Mpdreamz** [comment]
I've added a new version to nuget.org that targets `netstandard1.3` and behaves correctly on OSX and Windows.

**Pull request closed without merging**
